---
apiVersion: v1
kind: Namespace
metadata:
  name: evohome
  labels:
    app: evohome-exporter
---
apiVersion: v1
kind: Service
metadata:
  name: evohome-svc
  namespace: evohome
  labels:
    app: evohome-exporter
spec:
  selector:
    app: evohome-exporter
  type: ClusterIP
  ports:
    - name: metrics
      port: 8082
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: evohome-exporter-svcmon
  namespace: evohome
  labels:
    app: evohome-exporter
spec:
  jobLabel: evohome-exporter
  selector:
    matchLabels:
      app: evohome-exporter
  endpoints:
    - port: metrics
      interval: 60s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evohome-deploy
  namespace: evohome
  labels:
    app: evohome-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evohome-exporter
  template:
    metadata:
      labels:
        app: evohome-exporter
    spec:
      containers:
        - name: evohome-exporter
          image: localhost:32000/evohome-exporter:registry
          imagePullPolicy: "Always"
          ports:
            - name: metrics
              containerPort: 8082
          envFrom:
            - secretRef:
                name: evohome-credentials
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: tz
              mountPath: /etc/localtime
      volumes:
        - name: tz
          hostPath:
            path: /etc/localtime
