apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: persisted
  namespace: monitoring
spec:
  retention: 30d
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: microk8s-hostpath
        resources:
          requests:
            storage: 1Gi
