apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  loadBalancerIP: 192.168.1.60
  ports:
    - port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
  namespace: monitoring
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: alertmanager
  type: LoadBalancer
  loadBalancerIP: 192.168.1.60
  ports:
    - port: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.1.60
  ports:
    - port: 3000
